const {chromium}=require('playwright');
const {strict:assert}=require('node:assert');
const {randomBytes,createDecipheriv}=require('node:crypto');
const fs=require('node:fs/promises');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
(async()=>{
 const file=process.env.VAULT_HTML||path.resolve(__dirname,'../dist/离线私钥保险箱.html');
 const artifacts=path.resolve(__dirname,'../test-artifacts');await fs.mkdir(artifacts,{recursive:true});
 const executablePath=process.env.CHROME_PATH||(process.platform==='darwin'?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':undefined);
 const browser=await chromium.launch({executablePath,headless:true});
 const context=await browser.newContext({acceptDownloads:true,offline:true,viewport:{width:1360,height:1050}});
 const page=await context.newPage(); const errors=[],network=[];
 context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
 page.on('pageerror',e=>errors.push(e.message));
 context.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});
 try{
 await page.clock.install();
 await page.goto(pathToFileURL(file).href);
 await page.waitForSelector('#encrypt-text',{timeout:3000});
 assert.equal(await page.evaluate(()=>!!crypto.subtle),true);
 assert.equal(await page.evaluate(()=>typeof Vault?.seal),'function','The embedded crypto script must load under CSP');
 await page.screenshot({path:path.join(artifacts,'desktop.png'),fullPage:true});
 const fake='FAKE-WALLET-TEST-ONLY\n中文 🗝️ <img src="https://example.invalid/leak" onerror="alert(1)">\n  trailing spaces  ';
 await page.locator('#encrypt-text').fill(fake);
 assert.equal(await page.locator('#encrypt').isDisabled(),true);
 const kd=page.waitForEvent('download');await page.locator('#generate-key').click();
 const keyDownload=await kd;const kp=path.join(artifacts,'test.key');await keyDownload.saveAs(kp);
 assert.equal((await fs.readFile(kp)).length,40);
 // A wrong reselection must not silently replace the newly generated key.
 const wrong=path.join(artifacts,'wrong.key');await fs.writeFile(wrong,Buffer.concat([Buffer.from('PKEY0001'),randomBytes(32)]));
 await page.locator('#encrypt-key').setInputFiles(wrong);
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('刚生成'));
 assert.equal(await page.locator('#encrypt').isDisabled(),true);
 await page.locator('#encrypt-key').setInputFiles(kp);
 await page.waitForFunction(()=>!document.querySelector('#encrypt').disabled);
 const ed=page.waitForEvent('download');await page.locator('#encrypt').click();
 const exported=await ed;assert.ok(exported.suggestedFilename().endsWith('.vault'),'encrypted download must be a .vault file');const ep=path.join(artifacts,'encrypted.vault');await exported.saveAs(ep);
 const envelope=await fs.readFile(ep);
 assert.equal(envelope.subarray(0,8).toString(),'PVLT0001');
 assert.equal(envelope.length,Buffer.byteLength(fake)+36);
 assert.ok(!envelope.includes(Buffer.from('FAKE-WALLET-TEST-ONLY')));
 const rawKey=(await fs.readFile(kp)).subarray(8);assert.ok(!envelope.includes(rawKey));
 const dc=createDecipheriv('aes-256-gcm',rawKey,envelope.subarray(8,20));dc.setAAD(Buffer.from('PVLT0001'));dc.setAuthTag(envelope.subarray(-16));
 assert.equal(Buffer.concat([dc.update(envelope.subarray(20,-16)),dc.final()]).toString('utf8'),fake);
 const incomplete=path.join(artifacts,'incomplete.vault');
 await fs.writeFile(incomplete,envelope.subarray(0,-1));
 await page.locator('#verify-file').setInputFiles(incomplete);
 await page.waitForFunction(()=>!document.querySelector('#verify-file').disabled);
 assert.ok(!(await page.locator('#status').textContent()).includes('保存校验通过'),'incomplete export must not pass verification');
 assert.equal(await page.locator('#encrypt-text').inputValue(),fake);
 await page.locator('#encrypt-text').fill('new unsaved text');
 await page.locator('#verify-file').setInputFiles(ep);
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('保存校验通过'));
 assert.equal(await page.locator('#encrypt-text').inputValue(),'new unsaved text','verification must preserve newer input');
 const redownload=page.waitForEvent('download');await page.locator('#encrypt').click();
 const newDownload=await redownload,newFile=path.join(artifacts,'new-text.vault');await newDownload.saveAs(newFile);
 await page.locator('#verify-file').setInputFiles(newFile);
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('当前文本和密钥已清除'));
 assert.equal(await page.locator('#encrypt-text').inputValue(),'');
 assert.equal(await page.locator('#encrypt').isDisabled(),true);
 await page.locator('#tab-decrypt').click();
 await page.locator('#encrypted-file').setInputFiles(ep);
 await page.waitForFunction(()=>!document.querySelector('#decrypt-key').disabled);
 assert.equal(await page.locator('#encrypt-panel').isVisible(),false);
 assert.equal(await page.locator('#plain-output').isVisible(),false);
 await page.locator('#decrypt-key').setInputFiles(wrong);
 await page.waitForFunction(()=>!document.querySelector('#decrypt').disabled);
 await page.locator('#decrypt').click();
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('无法解密'));
 assert.equal(await page.locator('#plain-output').inputValue(),'');
 await page.locator('#decrypt-key').setInputFiles(kp);
 await page.waitForFunction(()=>!document.querySelector('#decrypt').disabled);
 await page.locator('#decrypt').click();
 await page.waitForFunction(()=>!document.querySelector('#reveal').disabled);
 assert.equal(await page.locator('#plain-output').inputValue(),'');
 await page.locator('#reveal').click();assert.equal(await page.locator('#plain-output').inputValue(),fake);
 await page.screenshot({path:path.join(artifacts,'decrypt.png'),fullPage:true});
 await page.evaluate(()=>window.dispatchEvent(new Event('blur')));
 assert.equal(await page.locator('#plain-output').inputValue(),'');
 await page.locator('#reveal').click();assert.equal(await page.locator('#plain-output').inputValue(),fake);
 await page.locator('#clear').click();assert.equal(await page.locator('#plain-output').inputValue(),'');
 assert.equal(await page.locator('#reveal').isDisabled(),true);
 // Tampered ciphertext must fail authentication.
 const damaged=Buffer.from(envelope);damaged[24]^=1;
 const tp=path.join(artifacts,'tampered.vault');await fs.writeFile(tp,damaged);
 await page.locator('#encrypted-file').setInputFiles(tp);
 await page.waitForFunction(()=>!document.querySelector('#decrypt-key').disabled);
 await page.locator('#decrypt-key').setInputFiles(kp);
 await page.waitForFunction(()=>!document.querySelector('#decrypt').disabled);await page.locator('#decrypt').click();
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('无法解密'));
 assert.equal(await page.locator('#plain-output').inputValue(),'');
 // Legacy exports remain readable as data, without running their executable content.
 const legacy=path.join(artifacts,'legacy.html');
 await fs.writeFile(legacy,'<script id="vault-payload" type="application/octet-stream">'+envelope.toString('base64')+'</script><script>window.LEGACY_EXECUTED=true</script>');
 await page.goto(pathToFileURL(file).href);await page.locator('#tab-decrypt').click();
 await page.locator('#encrypted-file').setInputFiles(legacy);
 await page.waitForFunction(()=>!document.querySelector('#decrypt-key').disabled);
 await page.locator('#decrypt-key').setInputFiles(kp);
 await page.waitForFunction(()=>!document.querySelector('#decrypt').disabled);await page.locator('#decrypt').click();
 await page.waitForFunction(()=>!document.querySelector('#reveal').disabled);await page.locator('#reveal').click();assert.equal(await page.locator('#plain-output').inputValue(),fake);
 assert.equal(await page.evaluate(()=>window.LEGACY_EXECUTED),undefined);
 await page.locator('#clear').click();await page.locator('#tab-encrypt').click();
 // Auto-clear runs against a simulated clock, exercising the real timer handler.
 await page.locator('#encrypt-text').fill('idle secret');
 await page.clock.fastForward(301000);
 assert.equal(await page.locator('#encrypt-text').inputValue(),'');
 assert.ok((await page.locator('#status').textContent()).includes('5 分钟'));
 // Clearing during a file read must not restore the key when that read completes.
 await page.evaluate(()=>{
   const original=File.prototype.arrayBuffer;
   File.prototype.arrayBuffer=function(){const file=this;return new Promise(resolve=>{window.finishKeyRead=async()=>resolve(await original.call(file));});};
 });
 await page.locator('#encrypt-key').setInputFiles(kp);
 await page.waitForFunction(()=>typeof window.finishKeyRead==='function');
 await page.locator('#clear').click();
 await page.evaluate(()=>window.finishKeyRead());
 await page.locator('#encrypt-text').fill('new content');
 assert.equal(await page.locator('#encrypt').isDisabled(),true);
 await page.locator('#clear').click();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(artifacts,'mobile.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.setViewportSize({width:800,height:1000});await page.evaluate(()=>document.documentElement.style.fontSize='200%');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(network,[]);assert.deepEqual(errors,[]);
 console.log('PASS: offline file workflow, downloaded-file verification, independent decryption, wrong keys, tampering, literal text, hiding/clearing, mobile/200% layout, no HTTP requests or JS errors.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
